# Generated by Django 3.2 on 2021-06-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
